"""Alpha-only Energy projection successor above the frozen BA12 runtime."""

from .compiler import build_alpha_energy_bundle
from .projection import (
    FRESHNESS_POLICY,
    FORMULA_REGISTRY,
    MAPPING_REGISTRY,
    OPERATING_METRICS_REQUIRING_PRIMARY_TEXT,
    PERIOD_BASIS_POLICY,
    RANKING_PROFILE,
    build_energy_semantic_artifacts,
    classify_period_basis,
)
from .v2 import (
    CORE_SLOT_REGISTRY_V2,
    DEBT_COMPARABILITY_CONTRACT_V2,
    ENERGY_PROFILE_V2_CANDIDATE,
    MAPPING_REGISTRY_V2,
    PERIOD_FRESHNESS_POLICY_V2,
    REVENUE_CONCEPT_FAMILY_V2,
    evaluate_energy_v2_case,
    registry_hashes,
    select_metric,
)
from .v3 import (
    AUTHORIZED_PERIOD_POLICY_SHA256,
    AUTHORIZED_SEMANTIC_SHA256,
    CAPEX_COMPARABILITY_CONTRACT_V3,
    CANDIDATE_INTEGRITY_CONTRACT_V3,
    CORE_SLOT_REGISTRY_V3,
    DEBT_COMPARABILITY_CONTRACT_V3,
    ENERGY_PROFILE_V3_CANDIDATE,
    ENERGY_SEMANTIC_CONTRACT_V3,
    PERIOD_FRESHNESS_POLICY_V3,
    REVENUE_COMPARABILITY_CONTRACT_V3,
    evaluate_energy_v3_case,
    inline_xbrl_candidates_v3,
    registry_hashes_v3,
    require_authorized_contract_v3,
    select_metric_v3,
    validate_candidate_integrity_v3,
)

__all__ = [
    "FRESHNESS_POLICY",
    "FORMULA_REGISTRY",
    "MAPPING_REGISTRY",
    "OPERATING_METRICS_REQUIRING_PRIMARY_TEXT",
    "PERIOD_BASIS_POLICY",
    "RANKING_PROFILE",
    "CORE_SLOT_REGISTRY_V2",
    "DEBT_COMPARABILITY_CONTRACT_V2",
    "ENERGY_PROFILE_V2_CANDIDATE",
    "MAPPING_REGISTRY_V2",
    "PERIOD_FRESHNESS_POLICY_V2",
    "REVENUE_CONCEPT_FAMILY_V2",
    "build_alpha_energy_bundle",
    "build_energy_semantic_artifacts",
    "classify_period_basis",
    "evaluate_energy_v2_case",
    "registry_hashes",
    "select_metric",
    "CAPEX_COMPARABILITY_CONTRACT_V3",
    "AUTHORIZED_PERIOD_POLICY_SHA256",
    "AUTHORIZED_SEMANTIC_SHA256",
    "CANDIDATE_INTEGRITY_CONTRACT_V3",
    "CORE_SLOT_REGISTRY_V3",
    "DEBT_COMPARABILITY_CONTRACT_V3",
    "ENERGY_PROFILE_V3_CANDIDATE",
    "ENERGY_SEMANTIC_CONTRACT_V3",
    "PERIOD_FRESHNESS_POLICY_V3",
    "REVENUE_COMPARABILITY_CONTRACT_V3",
    "evaluate_energy_v3_case",
    "inline_xbrl_candidates_v3",
    "registry_hashes_v3",
    "require_authorized_contract_v3",
    "select_metric_v3",
    "validate_candidate_integrity_v3",
]
